### ISSUE TITLE
Python package + Licence

### ISSUE THREAD

**Issue by ahartikainen** [izmailovpavel/TTGP#3]
Hi, are you planning to make a python package from the current codebase? 

Also, a license for the codebase would be nice.

**Comment by izmailovpavel** [comment]
Hi, thanks for your interest. I am planning to finish the work on the repo some time soon. I am not sure if I will make a package out of it because it's main purpose is to provide the code to reproduce the experiments from our paper. I will look into making a package out of it, and also the licenses. I will probably not be able to do it until the middle of December, however.
